apiVersion: apps/v1
kind: Deployment
metadata:
  name: apacheb6
  namespace: grupob6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apacheb6
  template:
    metadata:
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs.paths: /var/log/apache2/*.log        

        co.elastic.logs/module: apache
        co.elastic.logs.fileset.access.enabled: "true"
        co.elastic.logs.fileset.error.enabled: "true"
        co.elastic.logs/processors.add_fields.fields.service: apacheb6
        co.elastic.logs/processors.add_fields.fields.env: grupob6
      labels:
        app: apacheb6
        env: grupob6
    spec:
      containers:
        - name: apache
          image: ebdocker2025/apacheb6:1.2
          ports:
            - containerPort: 80
