apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: grupo6
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: ZXhhbXBsZQ==
  MARIADB_USER: YWdlbnRl
  MARIADB_USER_PASSWORD: MHRyYUNsYXZl
  MARIADB_DATABASE: dmlkZW9qdWVnb3NfZGI=
