apiVersion: v1
kind: PersistentVolume
metadata:
  name: grupob6-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
  hostPath:
    path: /mnt/data/profesor

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grupob6-pvc
  namespace: grupo6
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
